import streamlit as st
import pandas as pd
from PIL import Image
import os

st.title("📋 Reports & Analytics")

st.markdown("""
Centralized view of all project outputs, metrics,
predictions, charts, and trading performance.
""")

st.divider()

# ==========================
# Metrics Summary
# ==========================

st.subheader("📊 Model Metrics")

metrics_path = "outputs/reports/metrics.txt"

if os.path.exists(metrics_path):

    with open(metrics_path, "r") as f:
        metrics = f.read()

    st.success("Metrics Report Loaded")

    st.code(metrics)

else:

    st.warning("metrics.txt not found")

st.divider()

# ==========================
# Predictions
# ==========================

pred_path = "outputs/predictions/predictions.csv"

if os.path.exists(pred_path):

    st.subheader("🔮 Latest Predictions")

    pred_df = pd.read_csv(pred_path)

    st.dataframe(
        pred_df.tail(20),
        width="stretch"
    )

else:

    st.warning("predictions.csv not found")

st.divider()

# ==========================
# Charts Section
# ==========================

st.subheader("📈 Generated Charts")

chart_files = [
    (
        "Feature Importance",
        "outputs/charts/feature_importance.png"
    ),
    (
        "Equity Curve",
        "outputs/charts/equity_curve.png"
    ),
    (
        "Strategy vs Buy & Hold",
        "outputs/charts/strategy_vs_buy_hold.png"
    ),
    (
        "RL Agent Performance",
        "outputs/charts/rl_equity_curve.png"
    )
]

for title, path in chart_files:

    if os.path.exists(path):

        st.markdown(f"### {title}")

        img = Image.open(path)

        st.image(
            img,
            width="stretch"
        )

st.divider()

# ==========================
# Project Summary
# ==========================

st.subheader("📌 Project Summary")

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric(
        "Prediction Model",
        "XGBoost"
    )

with col2:
    st.metric(
        "RL Agent",
        "PPO"
    )

with col3:
    st.metric(
        "Assets",
        "AAPL/MSFT/GOOG"
    )

with col4:
    st.metric(
        "Dashboard",
        "Ready"
    )

st.divider()

st.success("""
✅ Portfolio Optimization Completed

✅ Market Prediction Model Trained

✅ Risk Management Implemented

✅ Backtesting Completed

✅ PPO Reinforcement Learning Agent Trained

✅ Interactive Dashboard Ready
""")

st.info("""
This page provides a consolidated view of all
results generated by the AI Financial Trading System.
It can be used directly during faculty demonstration.
""")